name = "Hugo FTP"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-ftp/blob/master/LICENSE"
description = "A Hugo theme that mimics the visual style and navigation of a classic FTP server interface"
homepage = "https://github.com/yourusername/hugo-ftp"
tags = ["blog", "minimal", "responsive", "ftp", "retro", "monospace"]
features = ["responsive", "blog", "clean", "minimalist"]
min_version = "0.80.0"

[author]
  name = "Your Name"
  homepage = "https://yourwebsite.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
